stages:
  - build

default:
  image: $UDS_BUILDER_IMAGE
  tags:
    - docker

variables:
  BUILD_OPTIONS: --with CREATE_OPTIONS=--skip-sbom

build:
  stage: build
  script: |
    uds run create-standard-package $BUILD_OPTIONS

    find . -name "build/*.tar.zst" -print0 | while IFS= read -r -d '' pkg; do
        echo "Uploading $pkg to Nexus"
        curl -f -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
        --upload-file "$pkg" \
        "$NEXUS_BASE_URL/repository/files/uds-packages/$(basename "$pkg")"
    done
#   rules:
#     - if: '$CI_COMMIT_TAG'
#       when: always
#     # Rule 1: Run automatically on the default branch (e.g., 'main') for push events.
#     - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
#       when: manual
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#       when: never
#     # Rule 2: On any other branch, the job is available but must be started manually.
#     - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
#       when: manual
#     # Rule 3: Allow manual runs initiated via the "Run pipeline" button in the UI.
#     - if: '$CI_PIPELINE_SOURCE == "web"'
#       when: manual
